name: "Docker build"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string

jobs:
  build-push-cpu:
    runs-on: gha-runner-scale-set-k8s-v2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GCP registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}
          username: _json_key_base64
          password: ${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: containerfiles/swarm-node/swarm.containerfile
          platforms: linux/amd64
          tags: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:${{ inputs.tag }}-cpu
          cache-from: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-cpu
          cache-to: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-cpu,compression=zstd,mode=max
  # build-push-gpu:
  #   runs-on: gha-runner-scale-set-k8s-v2
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to GCP registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}
  #         username: _json_key_base64
  #         password: ${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}
  #     - name: Build and Push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         context: .
  #         file: Dockerfile.gpu
  #         platforms: linux/amd64
  #         tags: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:${{ inputs.tag }}-gpu
  #         cache-from: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-gpu
  #         cache-to: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-gpu,compression=zstd,mode=max
  # build-push-vastai:
  #   runs-on: gha-runner-scale-set-k8s-v2
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to GCP registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}
  #         username: _json_key_base64
  #         password: ${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}
  #     - name: Build and Push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         context: .
  #         file: Dockerfile.vastai
  #         platforms: linux/amd64
  #         tags: ${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:${{ inputs.tag }}-vastai
  #         cache-from: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-vastai
  #         cache-to: type=registry,ref=${{ vars.GCP_ARTIFACT_REGISTRY_URL }}/node-gensyn:cache-vastai,compression=zstd,mode=max
